name: youfunny
description: A Discord bot to replace iFunny picture and video URLs with direct embedded URLs.
version: 1.0.2
repository: https://www.github.com/tytydraco/youfunny

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  args: ^2.3.1
  http: ^0.13.4
  nyxx: ^3.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  very_good_analysis: ^3.0.1
